spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/studs
    username: postgres
    password: 777ser
  jpa:
    hibernate:
      ddl-auto: update

camunda.bpm.admin-user:
  id: admin
  password: admin
server:
  port: 9090